name: decisive.photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58979
title: decisive.photography - smell the street
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56810-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080e10'
    - '#fefefe'
    - '#bcc8ce'
    - '#6c757a'
    - '#8d003e'
  brandStrength: 0.3789188389200717
  lightness: 0.7062528929673135
  saturation: 0.5716514238156378
  rhythmicContrast: 0.8637648453004658
purpose: []
