name: decisive.photography
favicon: null
layout_spectrum: 0.24952
typography_spectrum: 0.21244
title: decisive.photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56810-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#00b6d9'
    - '#d7d7d7'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
