typography_spectrum: 0.21244
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#00b6d9'
    - '#d7d7d7'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50385
analytics:
  google: UA-56810-6
  facebook: null
  twitter: null
author:
  name: Daniel Durrans
  email: dan@durrans.com
name: decisive.photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: decisive.photography
purpose: []
