typography_spectrum: 0.21244
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#808080'
    - '#00b6d9'
    - '#d7d7d7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74708
analytics:
  google: UA-56810-6
  facebook: null
  twitter: null
author:
  name: Daniel Durrans
  email: dan@durrans.com
name: decisive.photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Profile
    url: 'http://durrans.com'
    type: external
  - name: Photography
    url: 'http://danieldurrans.com'
    type: external
  - name: About
    id: 59c533cc-528a-4ba6-872a-a9d0021ac5ff
    type: content
favicon: null
title: decisive.photography
purpose: []
