name: decisive.photography
favicon: null
layout_spectrum: 0.50314
typography_spectrum: 0.58979
title: decisive.photography - A street photography adventure by Daniel Durrans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3789188389200717
  lightness: 0.7062528929673135
  saturation: 0.5716514238156378
  rhythmicContrast: 0.8637648453004658
purpose: []
